### ISSUE TITLE
Palautteen antaminen lauseena

### ISSUE THREAD

**Issue by johannesvaltonen** [affecto/positiivisen-palautteen-keha#1]
Haetaan kaikkien työntekijöiden nimet ruudulle. Nimeä klikkaamalla pääsee antamaan palautetta yksittäiselle henkilölle. Palaute annetaan vapaatekstikenttään.

Raporttinäytöllä listataan kaikki työntekijät ja heidän saamansa palautteet.

**Comment by piiajuola** [comment]
Palautteen anto toimi Chrome + IE, mutta raportti vain Chrome.
Annoin IE:n kautta Antille palautetta ja tämä näkyi myös Chrome raportilla.
OK!
