### ISSUE TITLE
Työntekijöiden synkronointi AD:sta

### ISSUE THREAD

**Issue by johannesvaltonen** [affecto/positiivisen-palautteen-keha#2]
Haetaan AD:sta tietyn ryhmän käyttäjät, jotka synkronoidaan tietokantaan. Uudet käyttäjät lisätään, vanhoja päivitetään ja poistuneet käyttäjät deaktivoidaan.

Haetaan käyttäjän ID, nimi, paikkakunta ja kuva.

Näytetään työntekijöiden kuvat käyttöliittymässä.

**Comment by piiajuola** [comment]
Muistetaan myös Karttakeskus.

**Comment by piiajuola** [comment]
Moi,
 
Osalla entisistä Affectolaisista on tunnus vielä disbloimatta, heillä on tunnukset pois siten että tunnarilla on "account expires" päivä. Jos hakuehtoon saa lisättyä "account expires"<today, niin tuo siivonnee ne.
 
Syystä tai toisesta Ekmanille ei ole HR laittanut mitään Department kenttään, se taisi olla yksi filtterin ehdoista, että siinä on jotain. Ehkäpä departmentin sijaan tsekataan vain että Company kentässä on arvo, sikäli mikäli joltain muultakin tuo Department arvo puuttuu.
 
terveisin,
Santtu

**Comment by piiajuola** [comment]
Moi,
 
Osalla entisistä Affectolaisista on tunnus vielä disbloimatta, heillä on tunnukset pois siten että tunnarilla on "account expires" päivä. Jos hakuehtoon saa lisättyä "account expires"<today, niin tuo siivonnee ne.
 
Syystä tai toisesta Ekmanille ei ole HR laittanut mitään Department kenttään, se taisi olla yksi filtterin ehdoista, että siinä on jotain. Ehkäpä departmentin sijaan tsekataan vain että Company kentässä on arvo, sikäli mikäli joltain muultakin tuo Department arvo puuttuu.
 
terveisin,
Santtu
