### ISSUE TITLE
Haku

### ISSUE THREAD

**Issue by johannesvaltonen** [affecto/positiivisen-palautteen-keha#5]
Työntekijöitä voi hakea nimen tai paikkakunnan mukaan. Hakutuloksia suodatetaan hakuehtoa kirjoittaessa.

**Comment by piiajuola** [comment]
Saako suodatuksessa näkyviin nimen ja kuvan (perustiedot)?

**Comment by piiajuola** [comment]
Haku ennen peukkuja

**Comment by piiajuola** [comment]
Ulkoasua: https://projects.invisionapp.com/share/855TOLHPG#/screens
